import React, { useMemo, useState } from "react"
import {
  AlertTriangle, CheckCircle2, Clock, FileText, Upload, ArrowRight, X,
  UserCheck, AlertCircle, Shield, Printer, ChevronRight, Check
} from "lucide-react"
import { StatusPill, btn, fieldBase, inr, fmtDate, useCases, useNotify, attempt, Hint } from "./ui"
import { InsuranceEngineService } from "../../services/insuranceDb"
import type { ComprehensiveClaimRecord } from "../../types/insurance"

// Gate checklist item
function GateItem({ done, label, sub, action, onAction }: {
  done: boolean; label: string; sub?: string; action?: string; onAction?: () => void
}) {
  return (
    <div className={`flex items-start gap-3 p-3.5 rounded-lg border ${done ? "bg-emerald-50 border-emerald-200" : "bg-amber-50 border-amber-200"}`}>
      <div className={`mt-0.5 w-5 h-5 rounded-full flex items-center justify-center shrink-0 ${done ? "bg-emerald-500" : "bg-amber-200"}`}>
        {done ? <Check size={11} className="text-white" /> : <AlertCircle size={11} className="text-amber-700" />}
      </div>
      <div className="flex-1 min-w-0">
        <div className={`text-xs font-semibold ${done ? "text-emerald-900" : "text-amber-900"}`}>{label}</div>
        {sub && <div className={`text-[11px] mt-0.5 ${done ? "text-emerald-700" : "text-amber-700"}`}>{sub}</div>}
      </div>
      {!done && action && (
        <button type="button" onClick={onAction} className="text-[10.5px] font-bold text-blue-600 hover:underline whitespace-nowrap">
          {action}
        </button>
      )}
    </div>
  )
}

// Summary row
function SummaryRow({ n, label, value, highlight }: { n?: number; label: string; value: string; highlight?: boolean }) {
  return (
    <div className={`flex items-center justify-between py-2 ${highlight ? "border-t border-slate-200 mt-1 pt-3" : ""}`}>
      <span className={`text-xs ${highlight ? "font-bold text-slate-900" : "text-slate-600"}`}>
        {n && <span className="text-slate-400 mr-1">{n}.</span>}
        {label}
      </span>
      <span className={`font-mono text-xs ${highlight ? "font-black text-blue-700 text-sm" : "font-semibold text-slate-800"}`}>{value}</span>
    </div>
  )
}

export default function DischargeFinalizationView({
  c,
  onBack,
}: {
  c: ComprehensiveClaimRecord
  onBack: () => void
}) {
  const { notify, toastNode } = useNotify()
  const [finalApprovalRef, setFinalApprovalRef] = useState("")
  const [finalApprovalAmt, setFinalApprovalAmt] = useState("")
  const [finalApprovalDate, setFinalApprovalDate] = useState("")
  const [finalApprovalNotes, setFinalApprovalNotes] = useState("")
  const [docUpload, setDocUpload] = useState(false)
  const [savedApproval, setSavedApproval] = useState(false)

  // Gate checks — in practice these would come from real state
  const gates = useMemo(() => [
    { done: c.status !== "DRAFT" && c.status !== "ELIGIBILITY_PENDING", label: "Policy verified and pre-auth obtained", sub: c.approvedPreAuthAmount ? `Approved ₹${c.approvedPreAuthAmount.toLocaleString()}` : undefined, action: "Open Pre-Auth" },
    { done: (c.documents?.filter(d => d.status === "Uploaded" || d.status === "Verified").length ?? 8) >= 9, label: "Core discharge documents uploaded (≥9/11)", sub: `${c.documents?.filter(d => d.status === "Uploaded" || d.status === "Verified").length ?? 8}/11 uploaded`, action: "Upload Now" },
    { done: savedApproval || c.status === "CLAIM_SUBMITTED" || c.status === "APPROVED" || c.status === "SETTLEMENT_PENDING", label: "Final approval reference recorded from insurer", sub: savedApproval ? `Ref: ${finalApprovalRef}` : "Required before discharge gate opens", action: "Enter Reference" },
    { done: true, label: "Final bill generated by billing counter", sub: "Auto-linked from IP Billing" },
    { done: true, label: "Treating doctor has signed the discharge summary", sub: "Dr. Suresh Reddy — 29 Sep 2026" },
  ], [c, savedApproval, finalApprovalRef])

  const allGatesDone = gates.every(g => g.done)
  const uploadedDocs = c.documents?.filter(d => d.status === "Uploaded" || d.status === "Verified").length ?? 8

  return (
    <div className="flex-1 flex flex-col h-full bg-slate-50/70 overflow-y-auto">
      {toastNode}

      {/* Header */}
      <header className="bg-white border-b border-slate-200 px-6 py-4 space-y-3">
        <div className="flex items-center gap-2 text-xs text-slate-500 font-medium">
          <button type="button" onClick={onBack} className="hover:underline flex items-center gap-1">
            <ArrowRight size={13} className="rotate-180" /> Back
          </button>
          <span>&rsaquo;</span>
          <span className="text-slate-900 font-semibold">Discharge &amp; Final Approval</span>
        </div>
        <div className="flex items-center justify-between gap-4">
          <div>
            <h1 className="text-lg font-bold text-slate-900">{c.patientName}</h1>
            <div className="flex items-center gap-3 text-xs text-slate-500 mt-0.5 font-mono">
              <span>{c.mrn || c.patientId}</span>
              <span>·</span>
              <span>{c.policy.insurerName}</span>
              <StatusPill status={c.status} />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button type="button" className={`${btn.soft} gap-1.5`}>
              <Printer size={13} /> Print Summary
            </button>
            <button
              type="button"
              disabled={!allGatesDone}
              className={`${btn.primary} gap-1.5 disabled:opacity-40 disabled:cursor-not-allowed`}
              onClick={() => notify("Discharge gate opened — patient cleared for discharge", "success")}
            >
              <UserCheck size={14} /> {allGatesDone ? "Initiate Discharge" : "Discharge Blocked"}
            </button>
          </div>
        </div>
      </header>

      <div className="p-6 grid grid-cols-1 lg:grid-cols-12 gap-6">

        {/* Left: Discharge Gate Checklist */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-2xs">
            <h2 className="text-sm font-bold text-slate-900 mb-4 flex items-center gap-2">
              <Shield size={15} className="text-blue-600" />
              Discharge Gate Checklist
            </h2>
            <div className="space-y-2">
              {gates.map((g, i) => (
                <GateItem
                  key={i}
                  done={g.done}
                  label={g.label}
                  sub={g.sub}
                  action={!g.done ? g.action : undefined}
                />
              ))}
            </div>

            {allGatesDone ? (
              <div className="mt-4 p-3 bg-emerald-50 border border-emerald-200 rounded-lg text-xs font-semibold text-emerald-800 flex items-center gap-2">
                <CheckCircle2 size={14} /> All gates passed — discharge may proceed
              </div>
            ) : (
              <div className="mt-4 p-3 bg-rose-50 border border-rose-200 rounded-lg text-xs font-semibold text-rose-800 flex items-center gap-2">
                <AlertTriangle size={14} /> {gates.filter(g => !g.done).length} gate{gates.filter(g => !g.done).length !== 1 ? "s" : ""} pending — discharge is blocked
              </div>
            )}
          </div>
        </div>

        {/* Middle: Final Approval Form */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-2xs space-y-4">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <CheckCircle2 size={15} className="text-emerald-600" />
              Record Final Approval
            </h2>
            <Hint tone="blue">
              When the insurer emails the final approval, paste the reference number here. This unlocks the discharge gate.
            </Hint>
            <div className="space-y-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">Approval Reference / Letter No.</label>
                <input type="text" value={finalApprovalRef} onChange={e => setFinalApprovalRef(e.target.value)} placeholder="e.g. FA/2026/00154" className={`w-full ${fieldBase}`} />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">Approved Final Amount (₹)</label>
                <input type="number" value={finalApprovalAmt} onChange={e => setFinalApprovalAmt(e.target.value)} placeholder="e.g. 80500" className={`w-full ${fieldBase}`} />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">Approval Date</label>
                <input type="date" value={finalApprovalDate} onChange={e => setFinalApprovalDate(e.target.value)} className={`w-full ${fieldBase}`} />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">Notes / Deductions</label>
                <textarea value={finalApprovalNotes} onChange={e => setFinalApprovalNotes(e.target.value)} rows={3} placeholder="Any deductions, non-payables, or conditions…" className="w-full px-3 py-2 rounded-md border border-slate-300 text-xs text-slate-900 focus:outline-none focus:border-blue-400 resize-none" />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">Upload Approval Letter</label>
                <div className="border-2 border-dashed border-slate-200 rounded-lg p-3 text-center text-xs text-slate-400 hover:border-blue-300 cursor-pointer">
                  <Upload size={14} className="mx-auto mb-1" />
                  Drag or click to upload PDF / image
                </div>
              </div>
            </div>
            <div className="flex gap-2 pt-1">
              <button
                type="button"
                disabled={!finalApprovalRef || !finalApprovalAmt}
                className={`flex-1 ${btn.primary} disabled:opacity-40 disabled:cursor-not-allowed`}
                onClick={() => {
                  setSavedApproval(true)
                  notify("Final approval recorded — discharge gate updated", "success")
                }}
              >
                Save Final Approval
              </button>
            </div>
          </div>
        </div>

        {/* Right: Bill Summary */}
        <div className="lg:col-span-3 space-y-4">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-2xs">
            <h2 className="text-sm font-bold text-slate-900 mb-4">Final Bill Summary</h2>
            <div className="divide-y divide-slate-100">
              <SummaryRow label="Approved Pre-Auth Amount" value={inr(c.approvedPreAuthAmount || 85000)} />
              <SummaryRow label="Total Billed (Final)" value={inr(c.consumedBillAmount || 92000)} />
              <SummaryRow label="Non-Payables" value="-₹5,000" />
              <SummaryRow label="Co-Pay (10%)" value="-₹9,200" />
              <SummaryRow label="Insurer Payable" value={inr(c.approvedPreAuthAmount || 80500)} highlight />
              <SummaryRow label="Patient Share" value="₹17,500" />
            </div>
            <div className="mt-4 pt-4 border-t border-slate-100">
              <div className="text-[11px] text-slate-500 mb-2">Document readiness</div>
              <div className="flex items-center gap-2">
                <div className="flex-1 h-2 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full bg-emerald-500 rounded-full" style={{ width: `${Math.round((uploadedDocs / 11) * 100)}%` }} />
                </div>
                <span className="text-xs font-bold text-slate-700">{uploadedDocs}/11</span>
              </div>
            </div>
          </div>

          {/* Discharge checklist quick view */}
          <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-2xs">
            <h3 className="text-xs font-bold text-slate-700 mb-3">Discharge Documents</h3>
            {["Discharge Summary", "Case Sheet", "Final Bill", "Investigation Reports", "Medication List", "Patient Counseling Sheet"].map((doc, i) => (
              <div key={i} className="flex items-center gap-2 py-1.5 text-xs">
                <div className={`w-4 h-4 rounded border flex items-center justify-center shrink-0 ${i < 4 ? "bg-emerald-500 border-emerald-500" : "border-slate-300"}`}>
                  {i < 4 && <Check size={9} className="text-white" />}
                </div>
                <span className={i < 4 ? "text-slate-700" : "text-slate-400"}>{doc}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
